var q = 0, sentenceDraw = "";
var x = -200, cenamatic = false;
var camera, cameraCenama, scene, renderer;
var geometry, material, mesh;
var health;
var moveForward = false, moveBackward = false, moveLeft = false, moveRight = false;
var prevTime = performance.now();
var velocity = new THREE.Vector3();
var block;
//var blockPositions = [], blockPositionsL2 = [], blockPositionsL3 = [];
var exit = true;
var wall, button;
var canJump = true, jumping;
var interaction = 0, interactionRead = false;
var textBox = document.getElementById('textBox');
var practiceLvl = document.getElementById('PracticeLvl');
var blocker = document.getElementById('blocker');
var pause = document.getElementById('pauseScreen');
var death = document.getElementById('gameOver');
var levelName = document.getElementById('levelName');
var currentLevel = false;
var interval;
var wallCount = 0;
var coinCount = 0;