var Levels = {
	Practice: {
		Name: "Practice",
		Map: // Ten types of blocks. Twenty by four by twenty grid. "Block" = Block; 2 = UpTop; 3 = RightTop; 4 = DownTop; 5 = LeftTop; 6 = UpBottom; 7 = RightBottom; 8 = DownBottom; 9 = LeftBottom; "Blank" = Blank;
		// [["Blank","Blank","Blank","Blank"], ["Blank","Blank","Blank","Blank"], ["Blank","Blank","Blank","Blank"], ["Blank","Blank","Blank","Blank"], ["Blank","Blank","Blank","Blank"], ["Blank","Blank","Blank","Blank"], ["Blank","Blank","Blank","Blank"], ["Blank","Blank","Blank","Blank"], ["Blank","Blank","Blank","Blank"], ["Blank","Blank","Blank","Blank"], ["Blank","Blank","Blank","Blank"], ["Blank","Blank","Blank","Blank"], ["Blank","Blank","Blank","Blank"], ["Blank","Blank","Blank","Blank"], ["Blank","Blank","Blank","Blank"], ["Blank","Blank","Blank","Blank"], ["Blank","Blank","Blank","Blank"], ["Blank","Blank","Blank","Blank"], ["Blank","Blank","Blank","Blank"], ["Blank","Blank","Blank","Blank"]]
		[
		[["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"]],
		[["Block","Block","Block","Blank"], ["Block","Block","Block","Block"], ["Block","Block","Block",5], ["Block","Block","Block",9], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block",7], ["Block","Block","Block",3], ["Block","Block","Block","Block"], ["Block","Block","Block","Blank"]],
		[["Block","Block","Block","Blank"], ["Block","Block","Block",2], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block",2,"Blank"], ["Block","Block",2,"Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block",2], ["Block","Block","Block","Blank"]],
		[["Block","Block","Block","Blank"], ["Block","Block","Block",6], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block",6,"Blank"], ["Block","Block",6,"Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block",6], ["Block","Block","Block","Blank"]],
		[["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"]],
		[["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"]],
		[["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block",2,"Blank","Blank"], ["Block",2,"Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"]],
		[["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block",6,"Blank","Blank"], ["Block",6,"Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"]],
		[["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Button","Blank","Blank"], ["Block","Blank","Blank","Blank"], ["Block","Blank","Blank","Blank"], ["Block","Button","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"]],
		[["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block",5,"Blank"], ["Block","Block",9,"Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block",5,"Blank","Blank"], ["Block",9,"Blank","Blank"], ["Block","Blank","Blank","Blank"], ["Block","Blank","Blank","Blank"], ["Block","Blank","Blank","Blank"], ["Block","Blank","Blank","Blank"], ["Block",7,"Blank","Blank"], ["Block",3,"Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block",7,"Blank"], ["Block","Block",3,"Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"]],
		[["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block",5,"Blank"], ["Block","Block",9,"Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block",5,"Blank","Blank"], ["Block",9,"Blank","Blank"], ["Block","Blank","Blank","Blank"], ["Block","Blank","Blank","Blank"], ["Block","Blank","Blank","Blank"], ["Block","Blank","Blank","Blank"], ["Block",7,"Blank","Blank"], ["Block",3,"Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block",7,"Blank"], ["Block","Block",3,"Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"]],
		[["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Button","Blank","Blank"], ["Block","Blank","Blank","Blank"], ["Block","Blank","Blank","Blank"], ["Block","Button","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"]],
		[["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block",8,"Blank","Blank"], ["Block",8,"Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"]],
		[["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block",4,"Blank","Blank"], ["Block",4,"Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"]],
		[["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"]],
		[["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"]],
		[["Block","Block","Block","Blank"], ["Block","Block","Block",8], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block",8,"Blank"], ["Block","Block",8,"Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Blank","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block",8], ["Block","Block","Block","Blank"]],
		[["Block","Block","Block","Blank"], ["Block","Block","Block",4], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block",4,"Blank"], ["Block","Block",4,"Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block",4], ["Block","Block","Block","Blank"]],
		[["Block","Block","Block","Blank"], ["Block","Block","Block","Block"], ["Block","Block","Block",5], ["Block","Block","Block",9], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block",7], ["Block","Block","Block",3], ["Block","Block","Block","Block"], ["Block","Block","Block","Blank"]],
		[["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"], ["Block","Block","Block","Blank"]]
		],
		PlayerPosition: {
			x: 200,
			y: 20,
			z: 200
		}
	}
}
